<?php
//移除警告
/** @var string $roleUrl */
/** @var string $addUrl */
/** @var string $roleId */
/** @var string $strHtml */

$roleUrl = $this->url . 'role';
$addUrl = $this->url . 'authorize';

return <<<STR
<a href="{$roleUrl}">角色列表</a>
<a href="javascript:void(0);">角色授权</a>
<form method="post">
{$strHtml}
<br>
<div>
    <button type="button" class="ajax-post" post_url="{$addUrl}" list_url="{$roleUrl}">
        保存
    </button>
    <input type="hidden" value="{$roleId}" name="role_id">
    <button type="button" onclick="javascript:history.go(-1)">返回</button>
</div>
</form>
<script>
    $(function () {
        $(".authorize_checkbox").unbind('click').click(function (e) {
            var is = $(this).prop('checked');
            var parent = $(this).attr('parent');
            var that;
            if (1 == parent) {
                that = $(this).parent().parent();
            } else {
                that = $(this).parent();
            }
            that.find('input[type="checkbox"]').each(function (i, ex) {
                if (is) {
                    $(this).prop("checked", true);
                } else {
                    $(this).prop("checked", false);
                }
            });
            var parent = $(this).parents('.authorize_check');
            for (var i = 0; i < parent.length; i++) {
                if (is) {
                    $($(parent[i]).find('input[type="checkbox"]').get(0)).prop("checked", true);
                }
            }
        });
    });
</script>
STR;


