<?php
//移除警告
/** @var string $roleUrl */
/** @var string $addUrl */
/** @var string $roleId */
/** @var string $strHtml */

$roleUrl = $this->url . 'role';
$addUrl = $this->url . 'authorize';

return <<<STR
<button class="_authmng-button-act" onclick="javascript:window.location.href='{$roleUrl}'">角色列表</button>
<button class="_authmng-button">角色授权</button>
<div class="_authmng-null"></div>
<form method="post">
{$strHtml}
<br>
<div>
    <button type="button" class="_authmng-submit _authmng-button" post_url="{$addUrl}" list_url="{$roleUrl}">
        保存
    </button>
    <input type="hidden" value="{$roleId}" name="role_id">
    <button type="button" onclick="javascript:window.history.go(-1)" class="_authmng-button">返回</button>
</div>
</form>
<script>
    $(function () {
        $("._authmng-authorize-checkbox").off('click').on('click',function (e) {
            var is = $(this).prop('checked');
            var parent = $(this).attr('parent');
            var that;
            if (1 == parent) {
                that = $(this).parent().parent();
            } else {
                that = $(this).parent();
            }
            that.find('input[type="checkbox"]').each(function (i, ex) {
                if (is) {
                    $(this).prop("checked", true);
                } else {
                    $(this).prop("checked", false);
                }
            });
            var parent = $(this).parents('._authmng-authorize-check');
            for (var i = 0; i < parent.length; i++) {
                if (is) {
                    $($(parent[i]).find('input[type="checkbox"]').get(0)).prop("checked", true);
                }
            }
        });
    });
</script>
STR;


