<?php
/** @var string $menuUrl */
/** @var string $addUrl */
/** @var array $upperLevel */

$menuUrl = $this->url . 'menu';
$addUrl = $this->url . 'menuAdd';

$_str = '';
foreach ($upperLevel as $upperLevelRow) {
    $_str .= '<option value="' . $upperLevelRow['id'] . '" ' . $upperLevelRow['selected'] . '>' . $upperLevelRow['name'] . '</option>';
}

return <<<HTML
<a href="{$menuUrl}">菜单列表</a>
<span>增加菜单</span>
<form method="post">
    <table class="table">
        <tbody>
        <tr>
            <td class="id_width">上级</th>
            <td>
                <select name="parent_id">
                    <option value="0">/</option>
                   {$_str}
                </select>
            </td>
        </tr>
        <tr>
            <td>名称</td>
            <td>
                <input type="text" name="name">
                <span>*</span>
            </td>
        </tr>
        <tr>
            <td>应用</td>
            <td>
                <input type="text" name="app">
                <span>*</span>
            </td>
        </tr>
        <tr>
            <td>控制器</td>
            <td>
                <input type="text" name="control">
                <span>*</span>
            </td>
        </tr>
        <tr>
            <td>方法</td>
            <td>
                <input type="text" name="action">
                <span>*</span>
            </td>
        </tr>
        <tr>
            <td>参数</td>
            <td>
                <input type="text" name="url_param">
                <span>例:id=3&amp;cid=3</span>
            </td>

        </tr>
        <tr>
            <td>排序</td>
            <td>
                <input type="text" name="sort">
            </td>
        </tr>
         <tr>
            <td>是否显示</td>
            <td>
                <input type="radio" name="is_show" value="1" checked> 显示
                <input type="radio" name="is_show" value="0"> 隐藏
            </td>
        </tr>
        <tr>
            <td>是否验证权限</td>
            <td>
                <input type="radio" name="is_verify" value="1" checked> 是
                <input type="radio" name="is_verify" value="0"> 否
            </td>
        </tr>
        <tr>
            <td>备注</td>
            <td>
                <textarea name="remark"></textarea>
            </td>
        </tr>
        </tbody>
    </table>
    </div>
    <div>
        <button type="button" class="ajax-post" post_url="{$addUrl}" list_url="{$menuUrl}">保存</button>
        <button type="button" onclick="javascript:history.go(-1)">返回</button>
    </div>
</form>
HTML;
