<?php
/** @var string $menuUrl */
/** @var string $addUrl */
/** @var array $upperLevel */
/** @var $list $upperLevel */

$menuUrl = $this->url . 'menu';
$addUrl = $this->url . 'menuAdd';

$_str = '';
foreach ($upperLevel as $upperLevelRow) {
    $_str .= '<option value="' . $upperLevelRow['id'] . '" ' . $upperLevelRow['selected'] . '>' . $upperLevelRow['name'] . '</option>';
}

if ($list['is_show']) {
    $status1 = 'checked';
    $status2 = '';
} else {
    $status1 = '';
    $status2 = 'checked';
}
if ($list['is_verify']) {
    $type1 = 'checked';
    $type2 = '';
} else {
    $type1 = '';
    $type2 = 'checked';
}

$xxxx = <<<HTML
<button class="_authmng-button-act" onclick="javascript:window.location.href='{$menuUrl}'">菜单列表</button>
<button class="_authmng-button">编辑菜单</button>
<div class="_authmng-null"></div>
<form method="post">
    <table class="_authmng-table">
        <tbody>
        <tr>
            <td class="_authmng-add-width">上级</td>
            <td>
                <select name="parent_id" class="_authmng-input">
                    <option value="0">/</option>
                   {$_str}
                </select>
            </td>
        </tr>
        <tr>
            <td>名称</td>
            <td>
                <input type="text" name="name" class="_authmng-input" value="{$list['name']}">
                <span>*</span>
            </td>
        </tr>
        <tr>
            <td>应用</td>
            <td>
                <input type="text" name="app" value="{$list['app']}" class="_authmng-input">
                <span>*</span>
            </td>
        </tr>
        <tr>
            <td>控制器</td>
            <td>
                <input type="text" name="control" value="{$list['control']}" class="_authmng-input">
                <span>*</span>
            </td>
        </tr>
        <tr>
            <td>方法</td>
            <td>
                <input type="text" name="action" value="{$list['action']}" class="_authmng-input">
                <span>*</span>
            </td>
        </tr>
        <tr>
            <td>参数</td>
            <td>
                <input type="text" name="url_param" value="{$list['url_param']}" class="_authmng-input">
                <span>例:id=3&amp;cid=3</span>
            </td>

        </tr>
        <tr>
            <td>排序</td>
            <td>
                <input type="text" name="sort" value="{$list['sort']}" class="_authmng-input">
            </td>
        </tr>
         <tr>
            <td>是否显示</td>
            <td>
                <input type="radio" name="is_show" value="1" {$status1}> 显示
                <input type="radio" name="is_show" value="0" {$status2}> 隐藏
            </td>
        </tr>
        <tr>
            <td>是否验证权限</td>
            <td>
                <input type="radio" name="is_verify" value="1" {$type1}> 是
                <input type="radio" name="is_verify" value="0" {$type2}> 否
            </td>
        </tr>
        <tr>
            <td>备注</td>
            <td>
                <textarea name="remark" class="_authmng-textarea">{$list['remark']}</textarea>
            </td>
        </tr>
        </tbody>
    </table>
    <br>
    <div>
        <input type="hidden" name="id" value="{$list['id']}">
        <button type="button" class="_authmng-submit _authmng-button" post_url="{$addUrl}" list_url="{$menuUrl}">保存</button>
        <button type="button" onclick="javascript:window.history.go(-1)" class="_authmng-button">返回</button>
    </div>
</form>
HTML;


return $xxxx;
