<?php
//移除警告
/** @var string $addRoleUrl */
/** @var string $authorize */
/** @var array $info */

$authorize = $this->url . 'authorize';
$addRoleUrl = $this->url . 'roleAdd';


$_str = '';
if ($info) {
    foreach ($info as $item) {
        $status = $item['status'] == 1 ? '有效' : '无效';
        $_str .= <<<STT
 <tr>
    <td>{$item['id']}</td>
    <td>{$item['name']}</td>
    <td>{$status}</td>
    <td>{$item['remark']}</td>
    <td>
        <a href="{$authorize}?role_id={$item['id']}">权限设置</a>
        <a href="{$addRoleUrl}?id={$item['id']}">编辑</a>
        <a href='javascript:void(0);' class="a-post" post-url="{$addRoleUrl}?id={$item['id']}&flag=d" post-msg="确定删除?">删除</a>
    </td>
</tr>
STT;
    }
}


return <<<STR
<a href="javascript:void(0);">角色列表</a>
<a href="{$addRoleUrl}">增加角色</a>

<table class="table">
    <thead>
    <tr>
        <th width="5%">ID</th>
        <th>名称</th>
        <th>状态</th>
        <th>备注</th>
        <th width="180">操作</th>
    </tr>
    </thead>
    <tbody>
    {$_str}
    </tbody>
</table>

STR;
