<?php
//移除警告
/** @var string $addRoleUrl */
/** @var string $authorize */
/** @var string $roleAdminUrl */
/** @var array $adminList */

$roleUrl = $this->url . 'role';
$adminAddUrl = $this->url . 'adminAdd';


$_str = '';
if ($adminList) {
    foreach ($adminList as $item) {
        $_str .= <<<STT
 <tr>
    <td>{$item['admin_id']}</td>
    <td>{$item['nickname']}</td>
    <td>{$item['name']}</td>
    <td>
        <a href="{$adminAddUrl}?id={$item['admin_id']}">编辑</a>
    </td>
</tr>
STT;
    }
}
$name = isset($_GET['name']) ? $_GET['name'] : '';

return <<<STR
<button class="_authmng-button-act" onclick="javascript:window.location.href='{$roleUrl}'">角色列表</button>
<button class="_authmng-button">角色下的管理员</button>
<div class="_authmng-null"></div>
<table class="_authmng-table">
    <thead>
    <tr>
        <th class="_authmng-id-width">管理员id</th>
        <th>昵称</th>
        <th>名称</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {$_str}
    </tbody>
</table>

STR;
