<?php
//移除警告
/** @var string $addRoleUrl */
/** @var string $authorize */
/** @var string $roleAdminUrl */
/** @var array $info */

$authorize = $this->url . 'authorize';
$addRoleUrl = $this->url . 'roleAdd';
$roleAdminUrl = $this->url . 'roleAdmin';


$_str = '';
if ($info) {
    foreach ($info as $item) {
        $status = $item['status'] == 1 ? '有效' : '无效';
        $_str .= <<<STT
 <tr>
    <td>{$item['id']}</td>
    <td>{$item['name']}</td>
    <td>{$status}</td>
    <td>{$item['remark']}</td>
    <td>
        <a href="{$roleAdminUrl}?role_id={$item['id']}&name={$item['name']}">管理员列表</a>&nbsp;
        <a href="{$authorize}?role_id={$item['id']}">权限设置</a>&nbsp;
        <a href="{$addRoleUrl}?id={$item['id']}">编辑</a>&nbsp;
        <a href='javascript:void(0);' class="_authmng-delete" post-url="{$addRoleUrl}?id={$item['id']}&flag=d" post-msg="确定删除?">删除</a>
    </td>
</tr>
STT;
    }
}


return <<<STR
<button class="_authmng-button">角色列表</button>
<button class="_authmng-button-act" onclick="javascript:window.location.href='{$addRoleUrl}'">增加角色</button>
<br>

<table class="_authmng-table">
    <thead>
    <tr>
        <th class="_authmng-id-width">ID</th>
        <th>名称</th>
        <th>状态</th>
        <th>备注</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {$_str}
    </tbody>
</table>

STR;
