<?php
/** @var string $addUrl */
/** @var string $roleUrl */

$addUrl = $this->url . 'roleAdd';
$roleUrl = $this->url . 'role';

return <<<STR
<a href="{$roleUrl}">角色列表</a>
<span>增加角色</span>
<form method="post">
    <table class="table">
        <tbody>
        <tr>
            <td class="_authmng-id-width">名称</td>
            <td>
                <input type="text" name="name"
                       value="">
                <span>*</span>
            </td>
        </tr>
        <tr>
            <td>备注</td>
            <td>
                <textarea name="remark"></textarea>
            </td>
        </tr>
        <tr>
            <td>状态</td>
            <td>
                <input type="radio" name="status"
                       value="1" checked> 有效
                <input type="radio" name="status" value="0"> 无效
            </td>
        </tr>

        </tbody>
    </table>
    </div>

    <div>
        <button type="button" class="_authmng-submit" post_url="{$addUrl}" list_url="{$roleUrl}">
            保存
        </button>
        <button type="button" onclick="javascript:history.go(-1)">返回</button>
    </div>
</form>
STR;
