<?php
/** @var string $addUrl */
/** @var string $roleUrl */
/** @var array $list */

$addUrl = $this->url . 'roleAdd';
$roleUrl = $this->url . 'role';

if ($list['status']) {
    $status1 = 'checked';
    $status2 = '';
} else {
    $status1 = '';
    $status2 = 'checked';
}

return <<<STR
<button class="_authmng-button-act" onclick="javascript:window.location.href='{$roleUrl}'">角色列表</button>
<button class="_authmng-button">编辑角色</button>
<br>
<br>
<form method="post">
    <table class="_authmng-table">
        <tbody>
        <tr>
            <td class="_authmng-id-width">名称</td>
            <td>
                <input type="text" name="name" value="{$list['name']}" class="_authmng-input">
                <span>*</span>
            </td>
        </tr>
        <tr>
            <td>备注</td>
            <td>
                <textarea name="remark" class="_authmng-textarea">{$list['remark']}</textarea>
            </td>
        </tr>
        <tr>
            <td>状态</td>
            <td>
                <input type="radio" name="status" value="1" {$status1}> 有效
                <input type="radio" name="status" value="0" {$status2}> 无效
            </td>
        </tr>

        </tbody>
    </table>
    <br>
    <div>
        <input type="hidden" name="id" value="{$list['id']}">
        <button type="button" class="_authmng-submit _authmng-button" post_url="{$addUrl}" list_url="{$roleUrl}">
            保存
        </button>
        <button type="button" onclick="javascript:window.history.go(-1)" class="_authmng-button">返回</button>
    </div>
</form>
STR;
