<?php
/** @var string $addUrl */
/** @var string $roleUrl */
/** @var array $list */

$addUrl = $this->url . 'roleAdd';
$roleUrl = $this->url . 'role';

if ($list['status']) {
    $status1 = 'checked';
    $status2 = '';
} else {
    $status1 = '';
    $status2 = 'checked';
}

return <<<STR
<a href="{$roleUrl}">角色列表</a>
<span>角色编辑</span>
<br>
<form method="post">
    <table class="table">
        <tbody>
        <tr>
            <td class="id_width">名称</td>
            <td>
                <input type="text" name="name"
                       value="{$list['name']}">
                <span>*</span>
            </td>
        </tr>
        <tr>
            <td>备注</td>
            <td>
                <textarea name="remark">{$list['remark']}</textarea>
            </td>
        </tr>
        <tr>
            <td>状态</td>
            <td>
                <input type="radio" name="status"
                       value="1" {$status1}> 有效
                <input type="radio" name="status" value="0" {$status2}> 无效
            </td>
        </tr>

        </tbody>
    </table>
    </div>

    <div>
        <input type="hidden" name="id" value="{$list['id']}">
        <button type="button" class="ajax-post" post_url="{$addUrl}" list_url="{$roleUrl}">
            保存
        </button>
        <button type="button" onclick="javascript:history.go(-1)">返回</button>
    </div>
</form>
STR;
